### ISSUE TITLE
In-house exposure that ends before the infection begins should be ignored

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/covid-calendar#61]
![Screenshot_2020-09-10 Covid Quarantine Qualculator](https://user-images.githubusercontent.com/2104990/92798809-215b4780-f368-11ea-98b4-b26e112084c2.png)

**Comment by wittejm** [comment]
Pretty sure this is a one-line addition somewhere in the calculator.

**Comment by KentShikama** [comment]
I think this is fine. The true start date of the infection is unknown. We could say any guidance to quarantine/isolate until a day before "today" could be removed, but then we will have to explain when we output blank results.

**Comment by wittejm** [comment]
Yep, makes sense about unknown contagion times. I've been staring at this comment for days because I can't decide in my head if showing end dates in the past is ok. Explaining blank results would just be "Alice does not need to quarantine" in the recommendations.

**Comment by wittejm** [comment]
Replacing this with #83
