### ISSUE TITLE
Option to save inputs in a cookie.

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/covid-calendar#68]
Client didn't love this idea because it "feels" like data collection. But it's not, and it's easy to build, and hopefully easy to explain e.g. in a tooltip. 

It could look like an unchecked box at the bottom that says, "save this data in my browser for later."

**Comment by KentShikama** [comment]
It could be an issue for public/shared computers.

**Comment by wittejm** [comment]
Generally doesn't seem like our preferred approach, so closing.
