### ISSUE TITLE
Show clearly if a person doesn't need to quarantine

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/covid-calendar#83]
The first is a bit non-obvious (because the date is past ), the second is incorrect because the person had no exposure or
![should say  freedom](https://user-images.githubusercontent.com/2104990/93633082-39078100-f9a3-11ea-9c7e-bb97af5d69c9.png)
 infection.

**Comment by KentShikama** [comment]
https://github.com/codeforpdx/covid-calendar/pull/89
